import { defineConfig } from 'drizzle-kit';

/**
 * ⚠️⚠️⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ⚠️⚠️⚠️
 *
 * This file is automatically regenerated by: scripts/db-studio-autodetect.mjs
 * When you run: pnpm run db:studio
 *
 * Purpose:
 *   - Inspect local miniflare D1 database with Drizzle Studio
 *   - Points to the current local SQLite file in .wrangler/state/
 *
 * Why auto-generated?
 *   - Database file path contains a unique hash per machine/database
 *   - Hash changes when database is recreated
 *   - Script auto-detects the current path and updates this file
 *
 * ⚠️ MANUAL EDITS TO THIS FILE WILL BE OVERWRITTEN
 *
 * To customize database path:
 *   1. Open: scripts/db-studio-autodetect.mjs
 *   2. Uncomment and set: MANUAL_DB_PATH = 'path/to/your/database.sqlite'
 *   3. Run: pnpm run db:studio (will use your manual path)
 *
 * Alternative:
 *   - Run drizzle-kit studio directly with your own config file
 *
 * No API credentials needed - just points to local SQLite file.
 */

export default defineConfig({
	schema: './src/lib/server/db/schema.ts',
	dialect: 'sqlite',
	dbCredentials: {
		// ⚠️ AUTO-DETECTED PATH - Will be overwritten on next run
		url: 'file:.wrangler/state/v3/d1/miniflare-D1DatabaseObject/88d0492543894f64faa3e01f1091557658117f6fe88b7e5c605836ba4f8b98b5.sqlite'
	}
});
